# Generated by Django 2.1.3 on 2018-11-10 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 8, 37, 38, 333781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 8, 37, 38, 335214, tzinfo=utc)),
        ),
    ]
